services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - GOOSE_PROVIDER=${GOOSE_PROVIDER}
        - GOOSE_MODEL=${GOOSE_MODEL}
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./db:/app/db
    env_file:
      - .env
    networks:
      - goosuke-network
    restart: unless-stopped
    # デバッグモードでアプリケーションを起動
    command: bash -c "python -B -m uvicorn api.main:app --host 0.0.0.0 --port 8000 --log-level debug"

networks:
  goosuke-network:
    driver: bridge