services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - GOOSE_PROVIDER=${GOOSE_PROVIDER}
        - GOOSE_MODEL=${GOOSE_MODEL}
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./db:/app/db
    env_file:
      - .env
    networks:
      - goosuke-network
    restart: unless-stopped
    # コンテナ内のPATHを確認するためのコマンド
    # command: bash -c "echo $$PATH && which goose || echo 'goose not found' && uvicorn api.main:app --host 0.0.0.0 --port 8000"

networks:
  goosuke-network:
    driver: bridge