"""remove config and context_rules columns from actions

Revision ID: 7a59f1094789
Revises: 6f48e9083678
Create Date: 2025-03-21 21:23:00.000000+09:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a59f1094789"
down_revision = "6f48e9083678"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. アクションテーブルから不要なカラムを削除
    op.drop_column("actions", "config")
    op.drop_column("actions", "context_rules")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 削除したカラムを復元
    op.add_column("actions", sa.Column("config", sa.JSON(), nullable=True))
    op.add_column("actions", sa.Column("context_rules", sa.JSON(), nullable=True))

    # ### end Alembic commands ###
